# Generated by Django 2.1.4 on 2020-01-19 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_teacher_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='tag',
            field=models.CharField(default='知名大学', max_length=10, verbose_name='机构标签'),
        ),
    ]
