# Generated by Django 2.1.4 on 2020-01-19 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20191206_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_banner',
            field=models.BooleanField(default=False, verbose_name='是否是轮播图'),
        ),
    ]
