# Generated by Django 2.1.4 on 2019-11-21 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourse',
            name='comments',
            field=models.CharField(default='空', max_length=50, verbose_name='描述信息'),
        ),
    ]
