"""
Django settings for MxOnline project.

Generated by 'django-admin startproject' using Django 2.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os
import sys

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(BASE_DIR, 'apps'))

# 如果将xadmin用于extra_apps文件夹时的注册项
# sys.path.insert(0, os.path.join(BASE_DIR, 'extra_apps'))  # 如果使用pycharm的source root的话也是可以的，但是脱离pycharm就不行了，所以还是有必要添加这项的

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'zg_!nlsh97)0@+$cxbh&ezy08vnl0cf(&p5wqqp8m89()zolmh'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# 关闭debug模式
# DEBUG = False
# ALLOWED_HOSTS = ['*']  # '*' 代表所有客户端都可以链接

# Application definition

# 改变登录验证过程
AUTHENTICATION_BACKENDS = (
    'users.views.CustomBackend',
)

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'users',
    'courses',
    'organization',
    'operation',
    'utils',

    'xadmin',  # 下面两项都是xadmin的注册
    'crispy_forms',

    'captcha',  # 验证码
    'pure_pagination',  # 分页
]
# 指定用户所用模型类
AUTH_USER_MODEL = "users.UserProfile"

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'MxOnline.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # 注册media url(也就是MEDIA_URL)
                'django.template.context_processors.media',
            ],
        },
    },
]

WSGI_APPLICATION = 'MxOnline.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'mxonline',
        'USER': 'root',
        'PASSWORD': '123456',
        'HOST': 'localhost',
        'PORT': 3306,
        'OPTIONS': {
            'init_command': 'SET sql_mode="STRICT_TRANS_TABLES"',
            'charset': 'utf8mb4'
        }

    }
}

# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False  # 时间存储为utc时间，所以要改为False，让时间变为本地时间

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'  # 当请求/static/时会去下面的这个目录寻找文件的
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "static"),
)

# 发送邮件的配置(sina)
EMAIL_HOST = "smtp.sina.com"
EMAIL_PORT = 25
EMAIL_HOST_USER = "rusiwillbeok@sina.com"  # 你的邮箱账号
EMAIL_HOST_PASSWORD = "289ad05e0b1163c3"  # 你的邮箱授权码
EMAIL_USE_TLS = False  # 这里是 False
EMAIL_FROM = "rusiwillbeok@sina.com"  # 你的邮箱账号

# 配置上传文件的路径(如果不配置的话，直接上传到工程目录里了)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# 生产环境nginx会代理静态文件，此时没有部署，所以要自己定义路由，
# STATIC_ROOT = os.path.join(BASE_DIR, 'static')


# 发送邮件的配置(163)
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# # 发邮件的smtp服务器地址
# EMAIL_HOST = 'smtp.163.com'
# EMAIL_PORT = 25
# # 发送邮件的邮箱
# EMAIL_HOST_USER = 'luola63702168@163.com'
# # 在邮箱中设置的客户端授权密码
# EMAIL_HOST_PASSWORD = 'La5205920'
# # 收件人看到的发件人
# EMAIL_FROM = '慕学网<luola63702168@163.com>'

# 分页的自定义配置信息
# PAGINATION_SETTINGS = {
#     'PAGE_RANGE_DISPLAYED': 5,  #　中间几个
#     'MARGIN_PAGES_DISPLAYED': 2,　#　省略号前后有几个
#
#     'SHOW_FIRST_PAGE_WHEN_INVALID': True,　#  参数为无效页的时候显示第一页
# }
